music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<problemset_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<problemset_id>[0-9]+)/(?P<problem_id>[0-9]+)/$', views.problemdetail, name='problemdetail'),
    url(r'^(?P<problemset_id>[0-9]+)/(?P<problem_id>[0-9]+)/(?P<submission_id>[0-9]+)/$', views.solution_verdict, name='solution_verdict'),
    url(r'^(?P<problem_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^problems/(?P<filter_by>[a-zA_Z]+)/$', views.problems, name='problems'),
    url(r'^create_problemset/$', views.create_problemset, name='create_problemset'),
    url(r'^(?P<problemset_id>[0-9]+)/create_problem/$', views.create_problem, name='create_problem'),
    url(r'^(?P<problemset_id>[0-9]+)/delete_problem/(?P<problem_id>[0-9]+)/$', views.delete_problem, name='delete_problem'),
    url(r'^(?P<problemset_id>[0-9]+)/favorite_problemset/$', views.favorite_problemset, name='favorite_problemset'),
    url(r'^(?P<problemset_id>[0-9]+)/delete_problemset/$', views.delete_problemset, name='delete_problemset'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
import datetime

class Problemset(models.Model):
    user = models.ForeignKey(User, default=1,on_delete=models.CASCADE)
    curator = models.CharField(max_length=250)
    problemset_title = models.CharField(max_length=500)
    problemset_type = models.CharField(max_length=100)
    problemset_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.problemset_title + ' - ' + self.curator


class Problem(models.Model):
    problemset= models.ForeignKey(Problemset, on_delete=models.CASCADE)
    problem_title = models.CharField(max_length=250)
    problem_file = models.FileField(default='')
    problem_expected_output = models.FileField(default='')
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.problem_title


class Submission(models.Model):
    problem = models.ForeignKey(Problem,on_delete=models.CASCADE)
    user = models.ForeignKey(User,default=1,on_delete=models.CASCADE)
    code = models.FileField(default='')
    my_output= models.FileField(default='')
    verdict = models.BooleanField()
    time= models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.problem.problem_title + " - " +self.time

music/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Problemset, Problem ,Submission


class ProblemsetForm(forms.ModelForm):

    class Meta:
        model = Problemset
        fields = ['curator', 'problemset_title', 'problemset_type', 'problemset_logo']


class ProblemForm(forms.ModelForm):

    class Meta:
        model = Problem
        fields = ['problem_title', 'problem_file','problem_expected_output']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class SubmissionForm(forms.ModelForm):

    class Meta:
        model = Submission
        fields = ['user', 'problem','code']

music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from  .forms import ProblemsetForm, ProblemForm, UserForm, SubmissionForm
from . models import Problemset, Problem ,Submission
from . import  forms
import requests
import json
import  datetime

TEXT_FILE_TYPES = ['pdf','txt']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


def create_problemset(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = ProblemsetForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            problemset = form.save(commit=False)
            problemset.user = request.user
            problemset.problemset_logo = request.FILES['problemset_logo']
            file_type = problemset.problemset_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'problemset': problemset,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/create_problemset.html', context)
            problemset.save()
            return render(request, 'music/detail.html', {'problemset': problemset})
        context = {
            "form": form,
        }
        return render(request, 'music/create_problemset.html', context)


def create_problem(request, problemset_id):
    form = ProblemForm(request.POST or None, request.FILES or None)
    problemset = get_object_or_404(Problemset, pk=problemset_id)
    if form.is_valid():
        problemsets_problems = problemset.problem_set.all()
        for s in problemsets_problems:
            if s.problem_title == form.cleaned_data.get("problem_title"):
                context = {
                    'problemset': problemset,
                    'form': form,
                    'error_message': 'You already added that problem',
                }
                return render(request, 'music/create_problem.html', context)
        problem = form.save(commit=False)
        problem.problemset = problemset
        #problem.problem_file = request.FILES['text_file']
        #file_type = problem.text_file.url.split('.')[-1]
        # file_type = file_type.lower()
        # if file_type not in TEXT_FILE_TYPES:
        #     context = {
        #         'problemset': problemset,
        #         'form': form,
        #         'error_message': 'Audio file must be WAV, MP3, or OGG',
        #     }
        #     return render(request, 'music/create_problem.html', context)

        problem.save()
        return render(request, 'music/detail.html', {'problemset': problemset})
    context = {
        'problemset': problemset,
        'form': form,
    }
    return render(request, 'music/create_problem.html', context)


def delete_problemset(request, problemset_id):
    problemset = Problemset.objects.get(pk=problemset_id)
    problemset.delete()
    problemsets = Problemset.objects.filter(user=request.user)
    return render(request, 'music/index.html', {'problemsets': problemsets})


def delete_problem(request, problemset_id, problem_id):
    problemset = get_object_or_404(Problemset, pk=problemset_id)
    problem = Problem.objects.get(pk=problem_id)
    problem.delete()
    return render(request, 'music/detail.html', {'problemset': problemset})


def detail(request, problemset_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        user = request.user
        problemset = get_object_or_404(Problemset, pk=problemset_id)
        return render(request, 'music/detail.html', {'problemset': problemset, 'user': user})



def problemdetail(request, problemset_id,problem_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        problem=get_object_or_404(Problem,pk=problem_id)
        form = SubmissionForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            submission = form.save(commit=False)
            submission.user = request.user
            submission.verdict=False
            submission.time=datetime.datetime.now()
            submission.save()

            return render(request, 'music/problemdetail.html', {'submission': submission})
        pn=problem.problem_title
        sub1 = Submission.objects.filter(problem__problem_title=pn).order_by('id')
        context = {
            'sub1':sub1,
            "form": form,
        }

        return render(request, 'music/problemdetail.html', context)



def solution_verdict(request,problemset_id,problem_id,submission_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        problem=get_object_or_404(Problem,pk=problem_id)
        p=problem.problem_expected_output.read()
        exp_out=str(p)
        submission=get_object_or_404(Submission,pk=submission_id)
        t=submission.code.read()
        d = t.decode('ASCII')
        exp_out=str(exp_out)
        exp_out=exp_out[2:-1]
        submission.my_output=exp_out
        payload = {"script": d,
                    "language": "c",
                   "versionIndex": "0",
                   "clientId": "c502938ae0bff7cc4d2d17553ea8a8bb",
                   "clientSecret": "85ce5b166d02a25e092f0057d3daebcf6f7b22cfd28d905d1f2b25166c915782",
                   }
        response = requests.post('https://api.jdoodle.com/execute', json=payload)
        data = json.loads(response.text)
        out=str(data['output'])
        if (data['output']==exp_out):
            submission.verdict=True
        else:
            submission.verdict=False
        submission.save()
        return render(request,'music/solution_verdict.html',{'out':out,'problem':problem,'submission':submission,'exp_out':exp_out})

def favorite(request, problem_id):
    problem = get_object_or_404(Problem, pk=problem_id)
    try:
        if problem.is_favorite:
            problem.is_favorite = False
        else:
            problem.is_favorite = True
        problem.save()
    except (KeyError, Problem.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def favorite_problemset(request, problemset_id):
    problemset = get_object_or_404(Problemset, pk=problemset_id)
    try:
        if problemset.is_favorite:
            problemset.is_favorite = False
        else:
            problemset.is_favorite = True
        problemset.save()
    except (KeyError, Problemset.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        problemsets = Problemset.objects.all()
        problem_results = Problem.objects.all()
        query = request.GET.get("q")
        if query:
            problemsets = problemsets.filter(
                Q(problemset_title__icontains=query) |
                Q(curator__icontains=query)
            ).distinct()
            problem_results = problem_results.filter(
                Q(problem_title__icontains=query)
            ).distinct()
            return render(request, 'music/index.html', {
                'problemsets': problemsets,
                'problems': problem_results,
            })
        else:
            return render(request, 'music/index.html', {'problemsets': problemsets})


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                problemsets = Problemset.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'problemsets': problemsets})
            else:
                return render(request, 'music/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'music/login.html', {'error_message': 'Invalid login'})
    return render(request, 'music/login.html')


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                problemsets = Problemset.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'problemsets': problemsets})
    context = {
        "form": form,
    }
    return render(request, 'music/register.html', context)


def problems(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        try:
            problem_ids = []
            for problemset in Problemset.objects.all():
                for problem in problemset.problem_set.all():
                    problem_ids.append(problem.pk)
            users_problems = Problem.objects.filter(pk__in=problem_ids)
            if filter_by == 'favorites':
                users_problems = users_problems.filter(is_favorite=True)
        except Problemset.DoesNotExist:

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CodeFii{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">CodeFii</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block problemsets_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; Problemsets</a></li>
                <li class="{% block problems_active %}{% endblock %}"><a href="{% url 'music:problems' 'all' %}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Problems</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_staff %}
                <li>
                    <a href="{% url 'music:create_problemset' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Problemset
                    </a>
                </li>
                {% endif %}
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CodeFii{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">CodeFii</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/create_song.html
{% extends 'music/base.html' %}
{% block title %}Add a New Problem{% endblock %}
{% block problemsets_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Problemset Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'music:detail' problemset.id %}">
                            {% if problemset.problemset_logo %}
                                <img src="{{ problemset.problemset_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h1>{{ problemset.problemset_title }} <small>{{ problemset.problemset_type }}</small></h1>
                    <h2>{{ problemset.curator }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Problem Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'music:detail' problemset.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:create_problem' problemset.id %}">Add New Problem</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Problem</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2" for="problem_title"><label for="id_problem_title">Problem title:</label></label>
        <div class="col-sm-10"><input id="id_problem_title" maxlength="250" name="problem_title" type="text" /></div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2" for="problem_title"><label for="id_audio_file">Text file:</label></label>
        <div class="col-sm-10"><input id="id_audio_file" name="audio_file" type="file" /></div>
    </div>



                        <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small"></span>
        </div>
        <label class="control-label col-sm-2" for="problem_title"><label for="id_audio_file">Expected Output:</label></label>
        <div class="col-sm-10"><input id="id_audio_file" name="audio_file" type="file" /></div>
    </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ problemset }}{% endblock %}
{% block problemsets_active %}active{% endblock %}

{% block body %}
<div class="container-fluid problems-container">

    <div class="row">

        <!-- Left Problemset Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' problemset.id %}">
                        {% if problemset.problemset_logo %}
                            <img src="{{ problemset.problemset_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ problemset.problemset_title }} <small>{{ problemset.problemset_type }}</small></h1>
                    <h2>{{ problemset.curator }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Problem Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' problemset.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:create_problem' problemset.id %}">Add New Problem</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Problems</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>File</th>
                            <th>Favorite</th>

                            <th>Actions</th>

                        </tr>
                        </thead>
                        <tbody>
                        {% for problem in problemset.problem_set.all %}
                            <tr>

                                <td> <a href="{% url 'music:problemdetail' problemset.id  problem.id %}" >{{ problem.problem_title }}</a> </td>
                                <td>
                                    <a target="_blank" href="{{ problem.problem_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-download"></span>&nbsp; Download
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'music:favorite' problem.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if problem.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'music:delete_problem' problemset.id problem.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="problem_id" value="{{ problem.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                                <td>


                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block problemsets_active %}active{% endblock %}

{% block body %}
<div class="problemsets-container container-fluid">

    <!-- Problemsets -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Problemsets</h3>
        </div>
        {% if problemsets %}
            {% for problemset in problemsets %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' problemset.id %}">
                            <img src="{{ problemset.problemset_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ problemset.problemset_title }}</h2>
                            <h4>{{ problemset.curator }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' problemset.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Problemset -->
                            <form action="{% url 'music:delete_problemset' problemset.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="problemset_id" value="{{ problemset.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Problemset -->
                            <a href="{% url 'music:favorite_problemset' problemset.id %}" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if problemset.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:create_problemset' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Problemset
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are problems -->
    {% if problems %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Problems</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Problem Title</th>
                                    <th>Curator</th>
                                    <th>Text File</th>
                                    <th>Problemset</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for problem in problems %}
                                    <tr>
                                        <td>{{ problem.problem_title }}</td>
                                        <td>{{ problem.problemset.curator }}</td>
                                        <td>
                                            <a target="_blank" href="{{ problem.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' problem.problemset.id %}">
                                                <img src="{{ problem.problemset.problemset_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' problem.problemset.id %}">{{ problem.problemset.problemset_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' problem.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if problem.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}